sudo: required
services:
  - docker

before_install:
  - docker build -t study221998/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true study221998/react-test npm test 

